# Generated by Django 5.2.14 on 2026-05-20 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalJobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hr_job_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("status", models.CharField(default="open", max_length=40)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExternalApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=200)),
                ("candidate_email", models.EmailField(max_length=254)),
                ("resume_text", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("sent_to_hr", models.BooleanField(default=False)),
                ("hr_application_id", models.IntegerField(blank=True, null=True)),
                (
                    "external_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="external_jobs.externaljobposting",
                    ),
                ),
            ],
        ),
    ]
